In [1]:
!nvidia-smi

Wed Sep 27 05:34:22 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 527.83       Driver Version: 527.83       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   53C    P8     4W /  17W |      0MiB /  2048MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
import torch
import numpy as np
torch.__version__

'2.0.1+cpu'

In [3]:
scalar = torch.tensor(9)
scalar

tensor(9)

In [4]:
scalar.ndim

0

In [5]:
vector = torch.tensor([3,4])
vector

tensor([3, 4])

In [6]:
vector.ndim

1

In [7]:
matrix = torch.tensor([[[2,6,4],
                       [8,7,9],
                       [9,388,3]],
                       [
                       [1,2,3],
                       [1,2,3],
                       [1,2,3]]])
matrix

tensor([[[  2,   6,   4],
         [  8,   7,   9],
         [  9, 388,   3]],

        [[  1,   2,   3],
         [  1,   2,   3],
         [  1,   2,   3]]])

In [8]:
matrix.ndim

3

In [9]:
matrix.shape

torch.Size([2, 3, 3])

In [10]:
random_tensor = torch.rand(5,3,2)
random_tensor

tensor([[[0.1824, 0.1084],
         [0.5696, 0.5650],
         [0.9132, 0.8991]],

        [[0.8196, 0.4595],
         [0.0134, 0.4884],
         [0.2603, 0.7253]],

        [[0.7092, 0.0112],
         [0.4477, 0.5345],
         [0.5362, 0.3728]],

        [[0.4715, 0.4363],
         [0.7048, 0.9739],
         [0.0138, 0.2547]],

        [[0.9035, 0.1001],
         [0.0841, 0.3302],
         [0.7456, 0.0684]]])

In [11]:
new = torch.tensor([0,1,3])
new+10,new*10,new-1

(tensor([10, 11, 13]), tensor([ 0, 10, 30]), tensor([-1,  0,  2]))

### Tensor Multiplication
1. Element wise 
2. Matrix multiplication (Dot product)

In [12]:
# Element wise
print(f"{new}*{new}={new*new}")

tensor([0, 1, 3])*tensor([0, 1, 3])=tensor([0, 1, 9])


In [13]:
%%time
# Matrix Multiplication
torch.matmul(new,new)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(10)

In [14]:
%%time
one = torch.tensor([[1,4],[3,5]])
two = torch.tensor([[2,4],[6,9]])
torch.matmul(one,two)

CPU times: total: 0 ns
Wall time: 0 ns


tensor([[26, 40],
        [36, 57]])

In [15]:
%%time
import numpy as np
w = np.array([[1,4],[3,5]])
w @ w

CPU times: total: 0 ns
Wall time: 0 ns


array([[13, 24],
       [18, 37]])

In [16]:
an = torch.arange(11,100,9)
an

tensor([11, 20, 29, 38, 47, 56, 65, 74, 83, 92])

In [17]:
torch.min(an),torch.max(an),torch.mean(an.type(torch.float32))

(tensor(11), tensor(92), tensor(51.5000))

In [18]:
torch.argmin(an),torch.argmax(an)

(tensor(0), tensor(9))

### PyTorch & Numpy

From Numpy -> PyTorch : torch.from_numpy(ndarray) 

From PyTorch -> Numpy : torch.Tensor.numpy( )