In [3]:
!nvidia-smi

Wed Sep 27 05:27:15 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 527.83       Driver Version: 527.83       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   50C    P8     4W /  17W |      0MiB /  2048MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [4]:
import torch
import numpy as np
torch.__version__

'2.0.1+cpu'

In [5]:
scalar = torch.tensor(9)
scalar

tensor(9)

In [6]:
scalar.ndim

0

In [7]:
vector = torch.tensor([3,4])
vector

tensor([3, 4])

In [8]:
vector.ndim

1

In [9]:
matrix = torch.tensor([[[2,6,4],
                       [8,7,9],
                       [9,388,3]],
                       [
                       [1,2,3],
                       [1,2,3],
                       [1,2,3]]])
matrix

tensor([[[  2,   6,   4],
         [  8,   7,   9],
         [  9, 388,   3]],

        [[  1,   2,   3],
         [  1,   2,   3],
         [  1,   2,   3]]])

In [10]:
matrix.ndim

3

In [11]:
matrix.shape

torch.Size([2, 3, 3])

In [12]:
random_tensor = torch.rand(5,3,2)
random_tensor

tensor([[[0.7883, 0.7453],
         [0.7475, 0.4885],
         [0.2489, 0.7371]],

        [[0.2116, 0.7152],
         [0.1914, 0.6055],
         [0.0992, 0.3381]],

        [[0.0544, 0.9755],
         [0.0216, 0.4739],
         [0.0763, 0.7827]],

        [[0.5153, 0.1970],
         [0.6641, 0.7498],
         [0.6114, 0.4038]],

        [[0.9787, 0.4672],
         [0.7072, 0.3738],
         [0.3306, 0.0848]]])

In [13]:
new = torch.tensor([0,1,3])
new+10,new*10,new-1

(tensor([10, 11, 13]), tensor([ 0, 10, 30]), tensor([-1,  0,  2]))

### Tensor Multiplication
1. Element wise 
2. Matrix multiplication (Dot product)

In [14]:
# Element wise
print(f"{new}*{new}={new*new}")

tensor([0, 1, 3])*tensor([0, 1, 3])=tensor([0, 1, 9])


In [15]:
%%time
# Matrix Multiplication
torch.matmul(new,new)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(10)

In [16]:
%%time
one = torch.tensor([[1,4],[3,5]])
two = torch.tensor([[2,4],[6,9]])
torch.matmul(one,two)

CPU times: total: 0 ns
Wall time: 0 ns


tensor([[26, 40],
        [36, 57]])

In [17]:
%%time
import numpy as np
w = np.array([[1,4],[3,5]])
w @ w

CPU times: total: 0 ns
Wall time: 0 ns


array([[13, 24],
       [18, 37]])

In [18]:
an = torch.arange(11,100,9)
an

tensor([11, 20, 29, 38, 47, 56, 65, 74, 83, 92])

In [19]:
torch.min(an),torch.max(an),torch.mean(an.type(torch.float32))

(tensor(11), tensor(92), tensor(51.5000))

In [20]:
torch.argmin(an),torch.argmax(an)

(tensor(0), tensor(9))

### PyTorch & Numpy

From Numpy -> PyTorch : torch.from_numpy(ndarray) 

From PyTorch -> Numpy : torch.Tensor.numpy( )

In [21]:
import random