In [2]:
!nvidia-smi

Wed Sep 27 17:58:34 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 527.83       Driver Version: 527.83       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   55C    P8     2W /  30W |    170MiB /  2048MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
import torch
import numpy as np
torch.__version__

'2.0.1+cpu'

In [4]:
scalar = torch.tensor(9)
scalar

tensor(9)

In [5]:
scalar.ndim

0

In [6]:
vector = torch.tensor([3,4])
vector

tensor([3, 4])

In [7]:
vector.ndim

1

In [8]:
matrix = torch.tensor([[[2,6,4],
                       [8,7,9],
                       [9,388,3]],
                       [
                       [1,2,3],
                       [1,2,3],
                       [1,2,3]]])
matrix

tensor([[[  2,   6,   4],
         [  8,   7,   9],
         [  9, 388,   3]],

        [[  1,   2,   3],
         [  1,   2,   3],
         [  1,   2,   3]]])

In [9]:
matrix.ndim

3

In [10]:
matrix.shape

torch.Size([2, 3, 3])

In [11]:
random_tensor = torch.rand(5,3,2)
random_tensor

tensor([[[0.1533, 0.0755],
         [0.9342, 0.1101],
         [0.6775, 0.7977]],

        [[0.8667, 0.0803],
         [0.4098, 0.4973],
         [0.2588, 0.9760]],

        [[0.3671, 0.9450],
         [0.4419, 0.2653],
         [0.5334, 0.6720]],

        [[0.7843, 0.2378],
         [0.0353, 0.6275],
         [0.4213, 0.9752]],

        [[0.4962, 0.5548],
         [0.4104, 0.2681],
         [0.6867, 0.7321]]])

In [12]:
new = torch.tensor([0,1,3])
new+10,new*10,new-1

(tensor([10, 11, 13]), tensor([ 0, 10, 30]), tensor([-1,  0,  2]))

### Tensor Multiplication
1. Element wise 
2. Matrix multiplication (Dot product)

In [13]:
# Element wise
print(f"{new}*{new}={new*new}")

tensor([0, 1, 3])*tensor([0, 1, 3])=tensor([0, 1, 9])


In [14]:
%%time
# Matrix Multiplication
torch.matmul(new,new)

CPU times: total: 0 ns
Wall time: 2 ms


tensor(10)

In [15]:
%%time
one = torch.tensor([[1,4],[3,5]])
two = torch.tensor([[2,4],[6,9]])
torch.matmul(one,two)

CPU times: total: 0 ns
Wall time: 2 ms


tensor([[26, 40],
        [36, 57]])

In [16]:
%%time
import numpy as np
w = np.array([[1,4],[3,5]])
w @ w

CPU times: total: 0 ns
Wall time: 1e+03 µs


array([[13, 24],
       [18, 37]])

In [17]:
an = torch.arange(11,100,9)
an

tensor([11, 20, 29, 38, 47, 56, 65, 74, 83, 92])

In [18]:
torch.min(an),torch.max(an),torch.mean(an.type(torch.float32))

(tensor(11), tensor(92), tensor(51.5000))

In [19]:
torch.argmin(an),torch.argmax(an)

(tensor(0), tensor(9))

### PyTorch & Numpy

From Numpy -> PyTorch : torch.from_numpy(ndarray) 

From PyTorch -> Numpy : torch.Tensor.numpy( )

In [20]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Random Seed

But what if you wanted to created two random tensors with the same values.

As in, the tensors would still contain random values but they would be of the same flavour.

That's where `torch.manual_seed(seed)` comes in, where seed is an integer (like 42 but it could be anything) that flavours the randomness.

In [21]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [22]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'